### ISSUE TITLE
Use polling based login flow

### ISSUE THREAD

**Issue by ammario** [cdr/coder-cli#1]
The existing localhost redirect solutions breaks when the browser is running on a different network than the command line (like in Coder Enterprise).

Instead, the CLI should publish a token to CE and link the browser to authenticate that token, then store that token locally. This is more secure too since the local token is different than the browser token.

A minimal RFC in the enterprise product should lay out the API in more detail first.

**Comment by cmoog** [comment]
The UX problem is fixed now.
