### ISSUE TITLE
Default to only environment & configurable default environment

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#104]
If you only have one environment, and you run a command that has an environment target (e.g. `coder sh` or `coder sync`) and you omit the target, we should just run the command against your only environment. Likewise, when you have multiple, you should be able to configure a default environment.

`gcloud` and `kubectl` both have default namespace / projects, so it would be similar to that.

Suggestion originally comes from @creack.

**Comment by creack** [comment]
Note that `coder config-ssh` uses the first env, but doesn't let you use a different one.

**Comment by cmoog** [comment]
> Note that coder config-ssh uses the first env, but doesn't let you use a different one.

I do not think this is correct. It only gives an _example_ using the first env but the SSH config file should get the spec for all of your environments.

**Comment by creack** [comment]
> > Note that coder config-ssh uses the first env, but doesn't let you use a different one.
> 
> I do not think this is correct. It only gives an _example_ using the first env but the SSH config file should get the spec for all of your environments. This command was modeled after `gcloud compute config-ssh`

Indeed, I was confused as the output is an example and differs slightly from the other commands. I confirm it indeed generates the config for all env! my bad.
