### ISSUE TITLE
Add input while waiting for oauth callback to allow ssh

### ISSUE THREAD

**Issue by creack** [cdr/coder-cli#107]
Right now, the cli login expects a HTTP callback, so when working over ssh, need to manually copy/paste the link into a different terminal and curl it. Having a text input to do the copy/paste directly on the cli would help a lot. (That's how concourse handles it for instance).
To be clear, that would be in addition of what we have, not instead.

**Comment by cmoog** [comment]
The current setup is definitely not good for browserless environments. Any thoughts on https://github.com/cdr/coder-cli/issues/1?

**Comment by creack** [comment]
I missed that, it is interesting indeed, but would be a much bigger change. Here, we can simply add something like `go os.Stdin.Read()` and call it a day.

#1 would indeed be a better user experience.
