### ISSUE TITLE
Consider removing formatting from errors

### ISSUE THREAD

**Issue by creack** [cdr/coder-cli#117]
We are making errors with newlines and formatting, like in coder-sdk/request.go. How the error is printed should be controlled by the logger and not by the error itself, especially when dealing with a lib. Some logger don't play well with newlines, some people having high log cost will prefer log only the most relevant part, or split the error between info/debug/error levels.

In most cases, it is just about removing newlines and punctuation, but in the case of the HTTP error, a common approach is to have a custom error type which can be used via errors.As or via errors.Unwrap + type assert. This is how part of the stdlib and sdks like was deal with this.

**Comment by cmoog** [comment]
This has been mostly resolved by our new use of specially formatted errors with package `clog`.
