### ISSUE TITLE
Document why we need to use MakeOutputRaw in the main

### ISSUE THREAD

**Issue by creack** [cdr/coder-cli#119]
It would be nice to add a comment explaining why we need to use MakeOutputRaw on windows in the main. It is a quite advance concept and while I am sure there is a reason (I am not familiar with windows) having an explanation there would help.

cc @cmoog @deansheather

**Comment by deansheather** [comment]
The purpose is to ensure vt100 codes (colors, formatting) work on windows. I'm unsure why we need to do it in main, though.

**Comment by cmoog** [comment]
`flog` prints colored output so I figured we might as well enable it in main.
