### ISSUE TITLE
Consider pulling org envs in parallel

### ISSUE THREAD

**Issue by creack** [cdr/coder-cli#121]
When someone has multiple orgs, we pull the list of envs for each orgs in sequence. We could make it parallel to speed up this use-case.

Reference: https://github.com/cdr/coder-cli/pull/113/files#diff-ca79b20149f2546be7e703c25ea64737R49-R58

cc @tychoish

**Comment by tychoish** [comment]
I think it'd be good to avoid hitting the web server multiple times for one logical operation (and getting all envs from an org in one go, seems like a reasonable request,) so while we could paralleliz, it'd probably be better to just use a different API (and we might need to add a new API, but that's easy enough,)

**Comment by wbobeirne** [comment]
We're moving towards top-level endpoints with query params instead of our current org-nested params, so this should be doable in a single request: https://github.com/cdr/c/blob/master/customer/service/cemanager/routes.go#L309-L310
