### ISSUE TITLE
Add rebuild command

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#127]
`coder rebuild [env]` should rebuild your environment as it's configured (not an edit command.) This is something you may want to do quickly from the CLI if you're editing / testing out your image, personalize script, or dotfiles repo. This will also be extremely useful with https://github.com/cdr/c/issues/3904, since otherwise you'd have to open your browser to be able to `coder sh`.

**Comment by cmoog** [comment]
If we're aiming to follow the existing command convention, this would be `coder envs rebuild [environment_name]`. Given that we've been discussing removing other resource types from the platform, namely secrets and services, it may be appropriate to revisit this choise.

**Comment by cmoog** [comment]
This is merged and awaiting as a hidden command awaiting feedback.

**Comment by cmoog** [comment]
Unhidden.
