### ISSUE TITLE
Integration tests shouldn't require bind mounts

### ISSUE THREAD

**Issue by deansheather** [cdr/coder-cli#128]
Bind mounts don't work within Coder enterprise because Docker runs in a different container to the main environment container, so it's impossible to run integration tests while dogfooding.

**Comment by deansheather** [comment]
This would be accomplishable by spawning a dud container that did nothing with a persistent volume attached, copying the files in with `docker cp` and then reusing that volume for all commands.

**Comment by cmoog** [comment]
The only reason we have bind mounts in `tcli` is to inject the CLI binary at startup. So we can definitely accomplish that in a more compatible way.

**Comment by deansheather** [comment]
Another solution @cmoog  would be to keep the binary in the home directory, as the home directory is mounted into sidecar containers.

**Comment by cmoog** [comment]
I don't think it makes sense to optimize our integration tests for the docker-in-docker case given that these will usually be running in an external CI pipeline. My latest attempt at fixing this also seems to be falling (https://github.com/cdr/coder-cli/pull/130) so I'm tempted to close this issue. Any objections?

**Comment by deansheather** [comment]
Not a big deal I guess, just means I'll have to run this locally
