### ISSUE TITLE
./coder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./coder)

### ISSUE THREAD

**Issue by misteliy** [cdr/coder-cli#141]
I get the error:

./coder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./coder)

my system:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by cmoog** [comment]
@misteliy Thank you for reporting this issue. It looks like we should be building with an older version of glibc. We'll have a patch up shortly.
