### ISSUE TITLE
macOS / Darwin release not signed

### ISSUE THREAD

**Issue by mchristopher** [cdr/coder-cli#26]
The binary release for the Darwin CLI isn't signed, and causes Gatekeeper to throw warnings when run. This is an issue in our environment as we require all installed binaries to be signed for security.

**Comment by coadler** [comment]
cc @nhooyr 

I'm not too familiar with MacOS binary signing. Any thoughts?

**Comment by nhooyr** [comment]
Found this tool that makes it pretty painless.

https://github.com/mitchellh/gon

**Comment by coadler** [comment]
Beautiful. Thanks.

**Comment by nhooyr** [comment]
@coadler Lmk how it goes, we might need something similar in code-server's macOS static releases.
