### ISSUE TITLE
Mouse inputs treated improperly in coder sh

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#29]
![Screen Shot 2020-05-26 at 4 19 17 PM](https://user-images.githubusercontent.com/649992/82951420-b890c080-9f6c-11ea-926c-765558d237a6.png)

Happens if I click on my terminal. Doesn't seem to happen in tmux, and mouse mode works fine with it, so not sure if there's anything too problematic here. Just feels a little jank.

**Comment by wbobeirne** [comment]
It's worth noting this behavior persists after the connection dies and I'm kicked out back to my terminal.

**Comment by cmoog** [comment]
This is fixed now.
