### ISSUE TITLE
Colon Missing in Login URL

### ISSUE THREAD

**Issue by CoderErik** [cdr/coder-cli#293]
When logging in using the CLI I receive the following message:
    The file /Users/erikbledsoe/https/master.cdr.dev/internal-auth?local_service=http:/127.0.0.1:54616 does not exist.
    Visit the following URL in your browser:
    
    	https//master.cdr.dev/internal-auth?local_service=http://127.0.0.1:54616

    or enter token manually:

The URL is missing the colon.

**Comment by vapurrmaid** [comment]
@CoderErik what was the exact command entered?

**Comment by CoderErik** [comment]
Fuck, my bad. I didn't type the colon when entering the command.
