### ISSUE TITLE
Use mutagen over SSH

### ISSUE THREAD

**Issue by ammario** [cdr/coder-cli#33]
... Now that we have this new shiny SSH server

cc @cmoog

**Comment by ammario** [comment]
I believe mutagen uses sftp to transfer the agent binary. That will need some confirmation.

**Comment by ammario** [comment]
Prioritizing because this has the potential to be a massive QoL improvement on the sync workflow.

**Comment by cmoog** [comment]
No plans to move forward with this at the moment.
