### ISSUE TITLE
Make one line install script

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#37]
Something like https://classic.yarnpkg.com/en/docs/install/#alternatives-stable that makes as few assumptions about the user's system, and works on as many systems as possible.

**Comment by cmoog** [comment]
This is mostly resolved by our new Homebrew tap `cdr/coder` at https://github.com/cdr/homebrew-coder

**Comment by nhooyr** [comment]
@cmoog won't it still be an issue for linux users?

**Comment by nhooyr** [comment]
or any non macOS users.

**Comment by nhooyr** [comment]
https://github.com/cdr/homebrew-coder/blob/25a309f42299d0a7d8ab3bcbf67992db7da6e016/coder-cli.rb#L11

is neat but I don't think anyone is going to install homebrew just for the coder cli.

**Comment by cmoog** [comment]
It comes pre-injected into the environment itself, and linux desktops are not common for our users. For installing into CI/automation pipelines, homebrew suffices for now.
