### ISSUE TITLE
Sign macOS release

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#39]
![Screen Shot 2020-06-12 at 4 25 53 PM](https://user-images.githubusercontent.com/649992/84547580-7b952f80-acc9-11ea-94d1-32a51aebe203.png)

This usually means we're not doing any kind of signing, we should sign the release even if we're not certified by Apple since it makes it more clear to the user that they can ignore the warning. This one requires you to know that you can go to security settings to override it.

**Comment by ammario** [comment]
Related #26

**Comment by wbobeirne** [comment]
Whoops yeah this is just a duplicate
