### ISSUE TITLE
Coder sh freezes

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#40]
I just had this happen for the first time ever, ~20 minutes after updating to the wsep version. After returning to my terminal after a bit of idling, it's completely unresponsive. No inputs are registered, ctrl+c / ctrl+d won't escape, I had to close the terminal and reconnect.

The old wush implementation would just kick me back out to my local session periodically, so I assume the disconnect that is happening isn't being gracefully treated with the wsep implementation.

**Comment by cmoog** [comment]
I've been able to replicate by rebuilding my env.
