### ISSUE TITLE
Clear screen after disconnect

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#51]
If you're in a "full screen" command like vim, nano, tmux etc. and you get disconnected, the whole screen keeps the characters from the full screen command. This can be really confusing. I'm pretty sure that ssh's default behavior on a disconnect is to clear the screen, but this might require a little testing about what most people would expect.

**Comment by cmoog** [comment]
We shell out to `ssh` directly, so this is no longer in our control.
