### ISSUE TITLE
login: Malformed login URL arg breaks login, sh and sync

### ISSUE THREAD

**Issue by Russtopia** [cdr/coder-cli#53]
As a naive user I tried

```coder login localhost:8080```
```coder login master.cdr.dev```

The browser auto-launch of the login URL is malformed in the above cases (and the text on terminal if autolaunch fails)

If I specify the full URL eg.
```coder login http://localhost:8080```

the URL generated is correct, and subsequent ```coder sh``` and ```coder sync``` ops work.

Recommend adding logic to prepend `http://` if not specified by the user.

**Comment by wbobeirne** [comment]
I think it'd be better to have them specify a full URI, since it could be https and they may not have redirects setup.

**Comment by Russtopia** [comment]
> I think it'd be better to have them specify a full URI, since it could be https and they may not have redirects setup.

Sorry, didn't see this until after I merged, but that's what I ended up doing. It doesn't try to fix up the incomplete URI -- it rejects and and the help/usage is updated to show an example. I can improve on it more if you think it should be more explicit.
