### ISSUE TITLE
Check that rsync protocol versions match before initiating transfer

### ISSUE THREAD

**Issue by ammario** [cdr/coder-cli#65]
So we can give the user a better error message than Exit Status 2

**Comment by stephenwithav** [comment]
Mind if I tackle this one?

I applied yesterday and want to demonstrate my Go proficiency.

Actions speak louder than words kinda thing. :)

**Comment by scsmithr** [comment]
Go for it.

Feel free to ping me when you have a PR up, and I can test it out against our Enterprise product.

**Comment by stephenwithav** [comment]
Will do. :)

**Comment by stephenwithav** [comment]
When #71 is merged, would you mind tagging some of the higher priority issues in `code-server`?

Anything that doesn't require a subscription I should have some time to knock out later this week.
