### ISSUE TITLE
Support and create a version compatible with Windows

### ISSUE THREAD

**Issue by nathanpotter** [cdr/coder-cli#67]

**Comment by Russtopia** [comment]
If there's not a hard requirement to stick to vanilla Windows, porting would be eased by leveraging MSYS
https://packages.msys2.org/package/rsync

**Comment by cmoog** [comment]
@nathanpotter Per your comment today about discouraging local ide workflows-- I'm thinking we should drop plans to support mutagen for now. It is only useful for local IDE workflows and requires SSH– unlike `coder sync`. 

Let's just hide `coder sync` behind a build flag for windows and replace it with an error message.

**Comment by cmoog** [comment]
It looks like we're also blocked by our PTY library https://github.com/creack/pty

**Comment by nathanpotter** [comment]
I agree^ one option is to just not support `coder sync` on windows and only build it into the tool for linux / darwin through go build flags / files

**Comment by ammario** [comment]
@nathanpotter's solution is the best initial way forward

**Comment by cmoog** [comment]
@nathanpotter @ammario totally agree. See https://github.com/cdr/coder-cli/issues/67#issuecomment-664026264. We're also blocked by `coder sh` seudo terminals.

**Comment by nathanpotter** [comment]
Are we able to utilize a different pty library that supports the various platforms?

**Comment by cmoog** [comment]
> Are we able to utilize a different pty library that supports the various platforms?

Unclear... still trying to find one.
