### ISSUE TITLE
Running 'coder urls' without any arguments errors

### ISSUE THREAD

**Issue by scsmithr** [cdr/coder-cli#82]
```
> coder urls
2020-07-30 10:30:44 INFO	found ["work" "nathan" "hello" "commit-judge" "mydev" "nix"]
2020-07-30 10:30:44 FATAL	environment "" not found
```

We should instead check that the environment name isn't empty. If it is, we should print usage.

**Comment by cmoog** [comment]
We should also move this towards a more standard argument hierarchy of `coder <resource> <verb> <identifier> <...flags>`. 

Something like 
```
coder urls ls <name>
coder urls rm <name>
coder urls create <name>
```

**Comment by cmoog** [comment]
Or... we could just move this to a subcommand of `coder envs`
