### ISSUE TITLE
Migrate to urfave/cli

### ISSUE THREAD

**Issue by cmoog** [cdr/coder-cli#85]
Although https://github.com/cdr/cli offers a minimal wrapper, it's becoming clear that it lacks sufficient features for the growing scope of `coder-cli`. I propose we migrate to ~https://github.com/spf13/cobra~ https://github.com/urfave/cli. Consider a few advantages that we'll gain "out of the box". 

- Suggestions when "unknown command" happens
- bash, zsh, fish, and powershell completion generation
- well designed and standard command validation abstractions
- better persistent flag abstractions
- no more interface upgrading nonsense
- the model of a separate type per command is flawed and, given the lack of generics, is very difficult to abstract

Any thoughts / objections? cc @scsmithr @nhooyr @ammario

**Comment by ammario** [comment]
I leave my vote to @nhooyr

**Comment by nhooyr** [comment]
So we discussed and we're gonna go with urfave/cli for more features and and improved API design that doesn't depend heavily on globals/init functions in comparison with cobra.

**Comment by nhooyr** [comment]
While cdr/cli is nice and minimal, it's definitely missing very useful features for users, especially in regards to completions and general UX.

**Comment by scsmithr** [comment]
I'm down to switch to whatever if y'all think it's an improvement.

**Comment by coadler** [comment]
+1 for urfave over cobra

**Comment by exvuma** [comment]
Tagging @khorne3 since this could help how she docs the CLI
