### ISSUE TITLE
Clean up secrets create UX

### ISSUE THREAD

**Issue by exvuma** [cdr/coder-cli#90]
```
$ coder secrets create new2 --from-prompt
value: ********
```

Should just be `$ coder secrets create new2` no flag needed. Also it's OK to not star out the value as long it's not shown in terminal history. It would be nice to let the user know again what key they are assigning to walk them through it and confirm that it was successful or not. 

e.g.

```
Enter your secret value for KEY:
...
Key KEY created successfully, access this key in any environment using $ coder get new2
```

**Comment by cmoog** [comment]
I strongly disagree that a terminal prompt should be the default behavior given how it would behave in scripts.  It should be clear to the user that the command requires stdin and will block until the proper input is given. The lack of a flag conceals this behavior. 

The prompt has a few other hidden downsides, including the difficultly of inputting multiline values. Hence, requiring the use of a flag forces the user to consider these trade-offs.

**Comment by exvuma** [comment]
That's not what's in the rfc or [what other CLIs do](https://slab.coder.com/posts/secrets-research-ida0bcqd). Can you address the other UX concerns?

**Comment by cmoog** [comment]
Entering the key through the terminal prompt creates unnecessary divergence from the other input methods. This is confusing and not necessary. 

The concealing of the input is a nice benefit for when the value is piped through stdin so as not to appear in the output at all.

**Comment by exvuma** [comment]
I avoid designing commands were flags are required, but agree to disagree. Closing this
