### ISSUE TITLE
Attempt to reconnect when coder sh disconnects randomly

### ISSUE THREAD

**Issue by wbobeirne** [cdr/coder-cli#94]
This is by far my biggest annoyance with `coder sh`, I get disconnected quite frequently. Could we attempt to reconnect for a second or two before dumping the user back to their terminal?

The issue is made even more annoying by #51 since it still looks like you're in your terminal if you're running tmux or some such.

**Comment by cmoog** [comment]
Yeah, this is definitely incredibly annoying. The trouble I'm having here is how to balance preventing process/connection leakage with a useful reconnection UX. Ideally, I'd like the solve the root of the disconnect problem but that has proved itself to be very difficult.

**Comment by cmoog** [comment]
A hacky solution could be that we reconnect and just create a new terminal session? @wbobeirne any thoughts on that?

**Comment by wbobeirne** [comment]
Hmm, I guess if the terminal session is lost, reconnecting might give the user the wrong impression if they expect everything to be as it was. I'd say if it has to be a new session, then we're probably better off with the explicit kill.

**Comment by cmoog** [comment]
We've fixed many of the disconnect conditions that were causing this. And now that we use `ssh` directly there isn't much for us to do in this arena.
